### ISSUE TITLE
Using prawn-gmagick on PNGs with an alpha channel results in a bloated file

### ISSUE THREAD

**Issue by tkfu** [packetmonkey/prawn-gmagick#14]
To minimally reproduce:
 Using [the attached test.png](https://user-images.githubusercontent.com/4501758/27843024-cb4cd41e-610f-11e7-85b1-90a6af63872c.png), run the following ruby script:

```ruby
require 'prawn'

pdf = Prawn::Document.new
pdf.text "Minimal test case"
pdf.image "test.png",:width => 500
pdf.render_file "test-prawn.pdf"

require 'prawn/gmagick'

pdf2 = Prawn::Document.new
pdf2.text "Minimal test case"
pdf2.image "test.png",:width => 500
pdf2.render_file "test-prawn-gmagick.pdf"
```
Then, look at the file sizes:
```
$ ls -lh *.pdf
-rw-rw-r-- 1 jon jon 884K Jul  4 23:16 test-prawn-gmagick.pdf
-rw-rw-r-- 1 jon jon  14K Jul  4 23:16 test-prawn.pdf
```
And check out the image object breakdown using the poppler suite:
```
$ pdfimages -list test-prawn.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    1804   499  rgb     3   8  image  no         7  0   260   260 3320B 0.1%
   1     1 smask    1804   499  gray    1   8  image  no         7  0   260   260 8869B 1.0%
$ pdfimages -list test-prawn-gmagick.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    1804   499  rgb     3   8  image  no         7  0   260   260 3528B 0.1%
   1     1 smask    1804   499  gray    1   8  image  no         7  0   260   260  879K 100%
```
Now, in this trivial case with a single tiny PNG using simple transparency, I added almost 900k to the pdf. When this first came up for real, I went from a 3MB pdf to an 80MB pdf.

**Comment by mojavelinux** [comment]
@packetmonkey This fix is vitally important for Asciidoctor PDF, which relies on prawn-gmagick to substantially decrease the time it takes to generate a PDF. Jon has submitted a PR. If there's anything I can do to help get this into a release, please don't hesitate to ask. Thanks in advance!

**Comment by mojavelinux** [comment]
@pointlessone would it be possible to get the associated PR merged?

**Comment by pointlessone** [comment]
@mojavelinux Which one is that?

**Comment by mojavelinux** [comment]
This one: https://github.com/packetmonkey/prawn-gmagick/pull/15

**Comment by pointlessone** [comment]
@mojavelinux I don't have access. I'm not involved with this project. I'm afraid it'll have to wait until Evan has some time.

**Comment by mojavelinux** [comment]
Thanks for the info!
